['text':'*
 * Tests that falling off a capped collection across a yield results in the correct error.
 ','line_number':1,'multiline':True]
['text':' Insert 10 documents.','line_number':15,'multiline':False]
['text':' The classic query engine may check for interrupt/check for yield a couple times before accessing','line_number':21,'multiline':False]
['text':' data, so 'internalQueryExecYieldIterations' must be set to a value slightly higher to ensure the','line_number':22,'multiline':False]
['text':' classic query engine has accessed data before deciding to yield.','line_number':23,'multiline':False]
['text':' Set the yield MS counter to a very high value so that we never yield due to time.','line_number':25,'multiline':False]
['text':' We use this try/finally pattern to ensure that the fail point gets disabled even if the test','line_number':31,'multiline':False]
['text':' fails.','line_number':32,'multiline':False]
['text':' In a separate shell, run the query.','line_number':34,'multiline':False]
['text':' Now do a bunch of inserts, rolling over the capped collection.','line_number':43,'multiline':False]
['text':' Unblock the thread doing the query by disabling the failpoint.','line_number':49,'multiline':False]
['text':' Join with the parallel shell.','line_number':53,'multiline':False]
