['text':'*
 * Tests the "failCommand" failpoint.
 *
 * @tags: [
 *   # The test runs commands that are not allowed with security token: whatsmyuri.
 *   not_allowed_with_signed_security_token,
 *   assumes_read_concern_unchanged,
 *   assumes_read_preference_unchanged,
 *   no_selinux,
 *   # This test expects that the connection (i.e. 'threadName') does not change throughout each
 *   # test case. That is not always true when there is a background tenant migration.
 *   tenant_migration_incompatible,
 *   does_not_support_repeated_reads,
 * ]
 ','line_number':1,'multiline':True]
['text':' Test idempotent configureFailPoint.','line_number':36,'multiline':False]
['text':' Configure failCommand again and verify that it still works correctly.','line_number':47,'multiline':False]
['text':' Test switching command sets.','line_number':60,'multiline':False]
['text':' Test failpoint with extraErrorInfo','line_number':83,'multiline':False]
['text':' Test failpoint with extraErrorInfo and no error code','line_number':105,'multiline':False]
['text':' Test failpoint for command aliases','line_number':120,'multiline':False]
['text':' Test failing with a particular error code.','line_number':138,'multiline':False]
['text':' Test that only commands specified in failCommands fail.','line_number':151,'multiline':False]
['text':' Test failing with multiple commands specified in failCommands.','line_number':168,'multiline':False]
['text':' Test skip when failing with a particular error code.','line_number':183,'multiline':False]
['text':' Test times when failing with a particular error code.','line_number':198,'multiline':False]
['text':' Commands not specified in failCommands are not counted for skip.','line_number':213,'multiline':False]
['text':' Commands not specified in failCommands are not counted for times.','line_number':231,'multiline':False]
['text':' Test closing connection.','line_number':249,'multiline':False]
['text':' Test that only commands specified in failCommands fail when closing the connection.','line_number':264,'multiline':False]
['text':' Test skip when closing connection.','line_number':283,'multiline':False]
['text':' Commands not specified in failCommands are not counted for skip.','line_number':300,'multiline':False]
['text':' Commands not specified in failCommands are not counted for times.','line_number':320,'multiline':False]
['text':' Cannot fail on "configureFailPoint" command.','line_number':340,'multiline':False]
['text':' Test with success and writeConcernError.','line_number':352,'multiline':False]
['text':' Commands that don't support writeConcern don't tick counter.','line_number':362,'multiline':False]
['text':' Unlisted commands don't tick counter.','line_number':364,'multiline':False]
['text':' Works again.','line_number':369,'multiline':False]
['text':' Test with natural failure and writeConcernError.','line_number':372,'multiline':False]
['text':' This document is removed before testing the following insert to prevent a DuplicateKeyError','line_number':374,'multiline':False]
['text':' if the failcommand_failpoint test is run multiple times on the same fixture.','line_number':375,'multiline':False]
['text':' Works again.','line_number':391,'multiline':False]
['text':' Test that specifying both writeConcernError and closeConnection : false will not make','line_number':394,'multiline':False]
['text':' `times` decrement twice per operation','line_number':395,'multiline':False]
['text':'','line_number':415,'multiline':False]
['text':' Test that the namespace parameter is obeyed.','line_number':416,'multiline':False]
['text':'','line_number':417,'multiline':False]
['text':' A find against a different namespace should not trigger the failpoint.','line_number':429,'multiline':False]
['text':' A find against the namespace given to the failpoint should trigger the failpoint.','line_number':432,'multiline':False]
['text':'','line_number':435,'multiline':False]
['text':' Test that the namespace parameter is obeyed for write concern errors.','line_number':436,'multiline':False]
['text':'','line_number':437,'multiline':False]
['text':' An insert to a different namespace should not trigger the failpoint.','line_number':449,'multiline':False]
['text':' An insert to the namespace given to the failpoint should trigger the failpoint.','line_number':453,'multiline':False]
['text':' Test failing with error labels will not make `times` decrement twice.','line_number':458,'multiline':False]
['text':' Test specifying both writeConcernError and errorLabels.','line_number':473,'multiline':False]
['text':' Test failCommand with empty errorLabels.','line_number':488,'multiline':False]
['text':' There should be no errorLabels field if no error labels provided in failCommand.','line_number':500,'multiline':False]
['text':' Test specifying both writeConcernError and empty errorLabels.','line_number':503,'multiline':False]
['text':' There should be no errorLabels field if no error labels provided in failCommand.','line_number':516,'multiline':False]
['text':' Test specifying errorLabels without errorCode or writeConcernError.','line_number':519,'multiline':False]
['text':' The command should not fail if no errorCode or writeConcernError specified.','line_number':525,'multiline':False]
['text':' As the command does not fail, there should not be any error labels even if errorLabels is','line_number':527,'multiline':False]
['text':' specified in the failCommand.','line_number':528,'multiline':False]
['text':' Test support for "appName" arg to failCommand','line_number':532,'multiline':False]
['text':' Only run error labels override tests for replica set because the tests require retryable writes.','line_number':557,'multiline':False]
['text':' And mongos doesn't return RetryableWriteError labels.','line_number':558,'multiline':False]
['text':' Test error labels override.','line_number':564,'multiline':False]
['text':' This normally fails with RetryableWriteError label.','line_number':575,'multiline':False]
['text':' Test that failCommand overrides the error label to "Foo".','line_number':580,'multiline':False]
['text':' Test error labels override while specifying writeConcernError.','line_number':583,'multiline':False]
['text':' This normally fails with RetryableWriteError label.','line_number':594,'multiline':False]
['text':' Test that failCommand overrides the error label to "Foo".','line_number':598,'multiline':False]
['text':' Test error labels override with empty errorLabels.','line_number':601,'multiline':False]
['text':' This normally fails with RetryableWriteError label.','line_number':612,'multiline':False]
['text':' There should be no errorLabels field if no error labels provided in failCommand.','line_number':617,'multiline':False]
['text':' Test error labels override with empty errorLabels while specifying writeConcernError.','line_number':620,'multiline':False]
['text':' This normally fails with RetryableWriteError label.','line_number':631,'multiline':False]
['text':' There should be no errorLabels field if no error labels provided in failCommand.','line_number':635,'multiline':False]
