['text':'!/usr/bin/env python','line_number':1,'multiline':False]['text':'','line_number':2,'multiline':False]['text':' Public Domain 2014-present MongoDB, Inc.','line_number':3,'multiline':False]['text':' Public Domain 2008-2014 WiredTiger, Inc.','line_number':4,'multiline':False]['text':'','line_number':5,'multiline':False]['text':' This is free and unencumbered software released into the public domain.','line_number':6,'multiline':False]['text':'','line_number':7,'multiline':False]['text':' Anyone is free to copy, modify, publish, use, compile, sell, or','line_number':8,'multiline':False]['text':' distribute this software, either in source code form or as a compiled','line_number':9,'multiline':False]['text':' binary, for any purpose, commercial or non-commercial, and by any','line_number':10,'multiline':False]['text':' means.','line_number':11,'multiline':False]['text':'','line_number':12,'multiline':False]['text':' In jurisdictions that recognize copyright laws, the author or authors','line_number':13,'multiline':False]['text':' of this software dedicate any and all copyright interest in the','line_number':14,'multiline':False]['text':' software to the public domain. We make this dedication for the benefit','line_number':15,'multiline':False]['text':' of the public at large and to the detriment of our heirs and','line_number':16,'multiline':False]['text':' successors. We intend this dedication to be an overt act of','line_number':17,'multiline':False]['text':' relinquishment in perpetuity of all present and future rights to this','line_number':18,'multiline':False]['text':' software under copyright law.','line_number':19,'multiline':False]['text':'','line_number':20,'multiline':False]['text':' THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,','line_number':21,'multiline':False]['text':' EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF','line_number':22,'multiline':False]['text':' MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.','line_number':23,'multiline':False]['text':' IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR','line_number':24,'multiline':False]['text':' OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,','line_number':25,'multiline':False]['text':' ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR','line_number':26,'multiline':False]['text':' OTHER DEALINGS IN THE SOFTWARE.','line_number':27,'multiline':False]['text':'','line_number':28,'multiline':False]['text':' test_txn18.py','line_number':29,'multiline':False]['text':'   Transactions: test recovery settings','line_number':30,'multiline':False]['text':'','line_number':31,'multiline':False]['text':' Here's the strategy:','line_number':59,'multiline':False]['text':'    - Create a table (t1).','line_number':60,'multiline':False]['text':'    - Insert data into t1.','line_number':61,'multiline':False]['text':'    - Simulate a crash.','line_number':62,'multiline':False]['text':'    - Make recovery run with recovery=error','line_number':63,'multiline':False]['text':' and make sure it detects an error since recovery is needed','line_number':64,'multiline':False]['text':'    - Make recovery run with recovery=on.','line_number':65,'multiline':False]['text':'    - Do a clean shutdown and restart with recovery=error','line_number':66,'multiline':False]['text':' and make sure is successful.','line_number':67,'multiline':False]['text':'','line_number':68,'multiline':False]['text':' If we aren't tracking file IDs properly, it's possible that','line_number':69,'multiline':False]['text':' we'd end up apply the log records for t2 to table t1.','line_number':70,'multiline':False]['text':'','line_number':73,'multiline':False]['text':' Since we're logging, we need to flush out the meta-data file','line_number':74,'multiline':False]['text':' from the create.','line_number':75,'multiline':False]['text':' close the original connection','line_number':86,'multiline':False]['text':' Trying to open the error directory with recover=error should return an error.','line_number':88,'multiline':False]['text':' If recover=error is run on the directory and returns an error,','line_number':93,'multiline':False]['text':' make sure when we subsequently open with recover=on it properly','line_number':94,'multiline':False]['text':' recovers all the data.','line_number':95,'multiline':False]['text':' Opening with recover=on should succeed.','line_number':99,'multiline':False]['text':' Make sure the data we added originally is there','line_number':101,'multiline':False]['text':' Reopening with recover=error after a clean shutdown should succeed.','line_number':112,'multiline':False]